# --- Basic site info ---
title: "Calendar Cop"
description: "Youth-activity conflict solver: paste calendars, see conflicts, fix in one click."

# If this is a *project site* (most likely):
# https://YOUR-USERNAME.github.io/calendar-cop/
url: "https://paneo66.github.io"
# baseurl: "/calendar-cop"      # ← keep this line for project pages

# If it's a *user/organization site* (https://YOUR-USERNAME.github.io):
# url: "https://YOUR-USERNAME.github.io"
# baseurl: ""                  # ← leave empty

# --- Theme (lightweight) ---
theme: jekyll-theme-minimal    # or: jekyll-theme-cayman / slate / hacker / modernist

# --- Plugins (GitHub-safe) ---
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# --- SEO / Social (optional but nice) ---
logo: /assets/icon.png         # put a 512x512 icon here if you have one
social:
  name: "Calendar Cop"
  links:
    - https://github.com/paneo66/calendar-cop
    # - https://twitter.com/yourhandle
    # - mailto:you@example.com

# --- Build options ---
markdown: kramdown
permalink: pretty

# Exclude files that shouldn't be published
exclude:
  - README.md                  # keep if you have index.html (README is for GitHub repo, not site)
  - node_modules/
  - .github/
  - .vscode/
  - "*.zip"

# Defaults (optional): turn off layout for raw HTML landing pages
defaults:
  - scope:
      path: ""                 # all files
      type: "pages"
    values:
      layout: null             # important if you use a custom index.html and don't want a theme wrapper
